[project]
authors = [{name = "Rocket-coder", email = "komarovo203@gmail.com"}]
dependencies = []
name = "experiment-hub"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
python = "3.12.*"
fastapi = ">=0.141.1,<0.142"
uvicorn = ">=0.52.4,<0.53"
pytest = ">=9.1.1,<10"
httpx = ">=0.28.1,<0.29"

[tool.pixi.pypi-dependencies]
experiment_hub = { path = ".", editable = true }

[tool.pixi.tasks]
dev = "fastapi dev src/experiment_hub/main.py"
test = "pytest"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]